export const defaultSettings = {
  version: "0.4",
  searchBar: true,
  searchEngine: "google",
  searchBarWidth: 300,
  iconVisibility: true,
  layoutStyle: "grid",
  iconLabel: true,
  iconOrder: "position",
  iconSize: 50,
  iconColumns: 5,
  iconGap: 20,
  backgroundType: "dark",
  bacfgroundColor: "#120312",
  backgroundUrl: "",
  backgroundTintIntensity: 0.5,
  blurValue: 0,
  iconBackground: false,
  iconBackgroundColor: "#8b8b8b",
  iconBackgroundOpacity: 0.17,
  iconBackgroundRadius: 26,
  accentColor: "#000000",
};
