export const defaultSettings = {
  version: "0.2",
  searchBar: true,
  searchEngine: "google",
  searchBarWidth: 300,
  iconVisibility: true,
  layoutStyle: "grid",
  iconLabel: true,
  iconOrder: "position",
  iconSize: 50,
  iconColumns: 5,
  iconGap: 20,
  backgroundType: "dark",
  bacfgroundColor: "#120312",
  backgroundUrl: "",
  backgroundTintIntensity: 0.5,
  blurValue: 0,
  iconBackground: true,
  iconBackgroundColor: "#ffffff",
  iconBackgroundOpacity: 0.9,
  iconBackgroundRadius: 50,
};
