export const firefoxDefaultSettings = {
  version: "0.5.3",
  detectedBrowserType: "firefox",
  searchBar: true,
  searchEngine: "google",
  searchBarWidth: 300,
  iconVisibility: true,
  layoutStyle: "grid",
  iconLabel: true,
  iconOrder: "position",
  iconSize: 50,
  iconColumns: 5,
  iconGap: 20,
  backgroundType: "dark",
  backgroundColor: "#000000",
  backgroundUrl: "",
  backgroundTintIntensity: 0.5,
  blurValue: 2.4,
  iconBackground: true,
  iconBackgroundColor: "#8b8b8b",
  iconBackgroundOpacity: 0.17,
  iconBackgroundRadius: 26,
  accentColor: "#000000",
  unsplashQuery: "",
  unsplashQuality: 1,
  unsplashFrequency: 4,
};
