export const firefoxDefaultSettings = {
  detectedBrowserType: "firefox",
  searchBar: true,
  searchEngine: "google",
  searchBarWidth: 300,
  iconVisibility: true,
  layoutStyle: "grid",
  iconLabel: true,
  iconOrder: "position",
  iconSize: 50,
  iconColumns: 5,
  iconGap: 20,
  backgroundType: "unsplash",
  backgroundColor: "#000000",
  backgroundUrl: "",
  backgroundTintIntensity: 0.4,
  blurValue: 3.6,
  iconBackground: true,
  iconBackgroundColor: "#8b8b8b",
  iconBackgroundOpacity: 0.17,
  iconBackgroundRadius: 26,
  accentColor: "#000000",
  unsplashQuery: "",
  unsplashQuality: 1,
  unsplashFrequency: 4,
  unsplashAutoRefresh: true,
};
